config/routes.rb
Rails.application.routes.draw do
  # Auth0 routes
  get "/auth/oauth2/callback" => "auth0#callback", as: 'auth0_callback'
  get "/auth/failure" => "auth0#failure"

  if Rails.env.development?
    post '/auth/developer/callback' => 'auth0#developer_callback'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/health' => 'health#show'
  get '/ping.json' => 'ping#show'
  get '/dashboard' => 'dashboard#show'
  get '/welcome' => 'welcome#show'
  get '/signup_not_allowed' => 'user_sessions#signup_not_allowed', as: 'signup_not_allowed'
  get '/signup_error/:error_type' => 'user_sessions#signup_error', as: 'signup_error'
  get '/' => 'home#show', as: 'root'

  resources :teams, param: :slug do
    scope :module => 'teams' do
      resources :members
      resources :permissions
    end
  end

  resources :services, param: :slug do
    scope :module => 'services' do
      resources :config_params, path: 'configuration'
      resources :permissions, controller_name: :service_permissions
      resources :deployments, controller_name: :service_deployments do
        get 'status', on: :collection, to: 'deployments#status'
        get '(/:env)', on: :collection, to: 'deployments#index', as: 'with_env', constraints: ServiceEnvironment::RoutingConstraint.new
        get 'log', on: :member, to: 'deployments#log'
      end
    end
  end


  resource :user
  resource :user_session, only: [:destroy]

  # global options responder -> makes sure OPTION request for CORS endpoints work
  match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
end

app/models/service.rb
class Service < ActiveRecord::Base
  include Concerns::HasSlug

  DEPLOY_KEY_REGEX = /\A[=+\/\n\rA-Za-z0-9 -]+\z/

  belongs_to :created_by_user, class_name: "User", foreign_key: :created_by_user_id

  has_many :service_config_params, dependent: :destroy
  has_many :permissions, dependent: :destroy
  has_many :teams, through: :permissions
  has_many :service_deployments, dependent: :destroy

  validates :name, length: {minimum: 3, maximum: 128}, uniqueness: true
  validates :git_repo_url, presence: true, length: {minimum: 8, maximum: 1024}
  validates :deploy_key, format: { with: DEPLOY_KEY_REGEX, allow_blank: true }
  validate  :check_git_repo_url

  after_create :generate_secret_config_params

  scope :contains, -> (name) { where("lower(name) like ?", "%#{name}%".downcase)}

  def service_token_for_environment(environment_slug)
    service_config_params.find_by(name: 'SERVICE_TOKEN', environment_slug: environment_slug)
  end

  # NOTE: uses same naive implementation as Team.visible_to -
  # two separate queries for IDs, then a single WHERE id IN(?)
  # Which will not scale well past a few hundred IDs
  def self.visible_to(user_or_user_id)
    user_id = user_or_user_id.is_a?(User) ? user_or_user_id.id : user_or_user_id
    service_ids = where(created_by_user_id: user_id).pluck(:id)
    service_ids += with_permissions_for_user(user_id).pluck(:id)

    where("id IN(?)", service_ids.uniq)
  end

  def is_visible_to?(user_or_user_id)
    user_id = user_or_user_id.is_a?(User) ? user_or_user_id.id : user_or_user_id

    created_by_user_id == user_id || \
      Permission.for_user_id(user_id).where(service_id: self.id).exists?
  end

  def self.with_permissions_for_user(user_id)
    joins(:permissions).joins(permissions: :team) \
                       .joins(permissions: {team: :members}) \
                       .where(team_members: {user_id: user_id})
  end

  private

  def generate_secret_config_params
    ServiceEnvironment.all_slugs.each do |slug|
      ServiceConfigParam.create(environment_slug: slug, name: 'SERVICE_TOKEN', value: SecureRandom.hex(16), service: self, last_updated_by_user: self.created_by_user, privileged: true)
      ServiceConfigParam.create(environment_slug: slug, name: 'SERVICE_SECRET', value: SecureRandom.hex(16), service: self, last_updated_by_user: self.created_by_user, privileged: true)
    end

    generate_public_private_keys
  end

  def generate_public_private_keys
    ServiceEnvironment.all_slugs.each do |slug|
      key_pair = PublicPrivateKey.new

      ServiceConfigParam.create(environment_slug: slug, name: 'ENCODED_PUBLIC_KEY', value: Base64.strict_encode64(key_pair.public_key), service: self, last_updated_by_user: self.created_by_user, privileged: true)
      ServiceConfigParam.create(environment_slug: slug, name: 'ENCODED_PRIVATE_KEY', value: Base64.strict_encode64(key_pair.private_key), service: self, last_updated_by_user: self.created_by_user, privileged: true)
    end
  end

  def check_git_repo_url
    if git_repo_url && git_repo_url.starts_with?('git@')
      uri = URI::SshGit.parse(git_repo_url)

      check_url_user_is_git(uri)
      check_url_host_is_github(uri)
      check_url_path_is_present(uri)
    else
      begin
        uri = URI.parse(self.git_repo_url)

        check_url_permitted_scheme(uri)
      rescue URI::InvalidURIError => e
        errors.add(:git_repo_url, I18n.t(:invalid_uri, scope: [:errors, :service, :git_repo_url]))
      end
    end
  end

  def check_url_permitted_scheme(uri)
    unless ['https', 'file', ''].include?(uri.scheme)
      errors.add(:git_repo_url, I18n.t(:not_valid_scheme, scope: [:errors, :service, :git_repo_url]))
    end
  end

  def check_url_user_is_git(uri)
    unless uri.user == 'git'
      errors.add(:git_repo_url, I18n.t(:not_valid_git, scope: [:errors, :service, :git_repo_url]))
    end
  end

  def check_url_host_is_github(uri)
    unless uri.host == 'github.com'
      errors.add(:git_repo_url, I18n.t(:not_valid_git, scope: [:errors, :service, :git_repo_url]))
    end
  end

  def check_url_path_is_present(uri)
    unless uri.path.present?
      errors.add(:git_repo_url, I18n.t(:not_valid_git, scope: [:errors, :service, :git_repo_url]))
    end
  end
end

app/controllers/services/config_params_controller.rb
class Services::ConfigParamsController < ApplicationController
  before_action :require_user!

  include ApplicationHelper
  include Concerns::NestedResourceController
  nest_under :service, attr_name: :slug, param_name: :service_slug

  before_action :load_and_authorize_resource!, only: [:edit, :update, :destroy]

  def index
    params[:env] ||= 'dev'
    params[:order] ||= 'name'

    @config_params = policy_scope(Service).find_by(id: @service.id)
                                          .service_config_params
                                          .where(environment_slug: params[:env])
                                          .unprivileged
                                          .order(params[:order] || :name)

    @environments = ServiceEnvironment.all
    @config_param = ServiceConfigParam.new( service: @service,
                                            environment_slug: params[:env] )
  end

  # called (remotely) from the "add" button in index
  def create
    @config_param = ServiceConfigParam.new(
      config_params_params.merge(
        service: @service,
        last_updated_by_user: @current_user
      )
    )
    authorize(@config_param)

    if @config_param.save
      flash[:success] = t(
          :success,
          scope: [:services, :config_params, :create],
          name: @config_param.name,
          environment: form_environment(@config_param.environment_slug)
      )
      redirect_to action: :index, service_id: @service, env: @config_param.environment_slug
    else
      flash[:error] = @config_param.errors.full_messages.join(', ')
      redirect_to service_config_params_path(@service, env: @config_param.environment_slug)
    end
  end

  def edit
    if request.xhr?
      render partial: 'form', locals: {config_param: @config_param}
    else
      # default
    end
  end

  def update
    if @config_param.update(
      config_params_params.merge(last_updated_by_user: current_user)
    )
      flash[:success] = t(
        :success,
        scope: [:services, :config_params, :update],
        name: @config_param.name,
        environment: form_environment(@config_param.environment_slug)
      )
      redirect_to action: :index,
                  env: @config_param.environment_slug
    else
      render :edit
    end
  end


  def destroy
    @config_param.destroy!
    redirect_to action: :index, service_id: @service, env: @config_param.environment_slug
  end

  private

  def load_and_authorize_resource!
    @config_param = @service.service_config_params.find(params[:id])
    authorize(@config_param)
  end

  def config_params_params( opts = params )
    opts.fetch(:service_config_param).permit(
      :environment_slug,
      :name,
      :service_id,
      :value
    )
  end
end

app/controllers/services/deployments_controller.rb
class Services::DeploymentsController < ApplicationController
  before_action :require_user!

  include Concerns::NestedResourceController
  include Pagy::Backend
  nest_under :service, attr_name: :slug, param_name: :service_slug

  before_action :load_and_authorize_resource!, only: [:edit, :update, :destroy, :show, :log]

  def index
    params[:per_page] ||= 10
    params[:page] ||= 1
    params[:order] ||= 'created_at'
    params[:dir] ||= 'desc'

    @environments = ServiceEnvironment.all
    @pagy, @deployments = pagy(ServiceDeployment.where(service: @service,
                                                       environment_slug: params[:env]).order("#{params[:order]} #{params[:dir]}"),
                               items: params[:per_page])

    @deployment = ServiceDeployment.new(service: @service, environment_slug: params[:env])
  end

  def status
    @environments = ServiceEnvironment.all
    @deployments_by_environment = DeploymentService.service_status(@service)
  end

  # called (remotely) from the "add" button in index
  def create
    @deployment = ServiceDeployment.new(
      deployments_params.merge(
        service: @service,
        created_by_user: @current_user,
        status: ServiceDeployment::STATUS[:queued]
      )
    )

    authorize(@deployment)

    if @deployment.save
      DeployServiceJob.perform_later(service_deployment_id: @deployment.id)
      redirect_to with_env_service_deployments_path(service_slug: @service, env: @deployment.environment_slug)
    else
      @environment = ServiceEnvironment.find(@deployment.environment_slug)
      render :new
    end
  end

  def edit
    if request.xhr?
      render partial: 'form', locals: {deployment: @deployment}
    else
      # default
    end
  end

  def new
    @deployment = ServiceDeployment.new(service: @service, environment_slug: params[:env])
    @environment = ServiceEnvironment.find(params[:env])
  end

  def destroy
    UndeployServiceJob.perform_later(env: @deployment.environment_slug.to_s, service_slug: @service.slug)
    @deployment.destroy!
    redirect_to action: :status
  end

  def show
    if request.xhr?
      render partial: 'deployment', locals: {deployment: @deployment}
    else
      # default
    end
  end

  def log
    @log_entries = JobLogService.entries(
      tag: DeployServiceJob.log_tag(@deployment.id),
      min_timestamp: params[:min_timestamp]
    )
    if request.xhr?
      render partial: 'log_entries', locals: {log_entries: @log_entries}
    else
      @environments = ServiceEnvironment.all
    end
  end

  private

  def load_and_authorize_resource!
    @deployment = @service.service_deployments.find(params[:id])
    authorize(@deployment)
  end

  def deployments_params( opts = params )
    opts.fetch(:service_deployment).permit(
      :environment_slug,
      :name,
      :service_id,
      :value,
      :json_sub_dir,
      :commit_sha
    )
  end
end

app/controllers/services/permissions_controller.rb
class Services::PermissionsController < ApplicationController
  before_action :require_user!

  include Concerns::NestedResourceController
  nest_under :service, attr_name: :slug, param_name: :service_slug

  before_action :load_and_authorize_resource!, only: [:edit, :update, :destroy]

  def index
    params[:order] ||= 'teams.name'
    # NOTE: no visible_to scope - we're assuming that all permissions of a service
    # can see each other.
    @permissions = @service.permissions
                      .includes(:team)
                      .order(params[:order] || 'users.name')
    @permission = Permission.new( service: @service )
    @possible_teams = Team.visible_to(current_user) - @service.teams
  end

  # called (remotely) from the "add" button in index
  def create
    @permission = Permission.new(
      permissions_params.merge(
        service: @service,
        created_by_user: @current_user
      )
    )

    begin
      team = find_or_create_team!
      @permission.team_id = team.id

      authorize(@permission)
      @permission.save!
      flash[:success] = I18n.t('services.permissions.create.success' )
      redirect_to action: :index, service_id: @service

    rescue StandardError => e
      permissions_error_message(e)
      redirect_to action: :index, service_id: @service
    end
  end

  def edit
    if request.xhr?
      render partial: 'form', locals: {permission: @permission}
    else
      # default
    end
  end

  def update
    if @permission.update(
      permissions_params.merge(created_by_user: current_user)
    )
      flash[:success] = t(
        :success,
        scope: [:services, :permissions, :update],
        name: @permission.name
      )
      redirect_to action: :index,
                  env: @permission.environment_slug
    else
      render :edit
    end
  end


  def destroy
    @permission.destroy!
    redirect_to action: :index, service_id: @service
  end

  private

  def load_and_authorize_resource!
    @permission = @service.permissions.find(params[:id])
    authorize(@permission)
  end

  def permissions_params( opts = params )
    opts.fetch(:permission).permit(
      :team_id,
      :service_id
    )
  end

  def permissions_error_message(e)
    scope = %i[services permissions create errors]
    flash[:error] = I18n.t(e.class.name.underscore.gsub('/', '_'),
                           scope: scope, message: e.class.name.underscore,
                           default: I18n.t(:default, scope: scope))
  end

  def find_or_create_team!(opts = params[:permission])
    if opts[:new_team].present?
      Team.create!(name: opts[:new_team], created_by_user: current_user)
    else
      Team.find(opts[:team_id])
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :require_user!
  before_action :load_and_authorize_resource!, only: [:edit, :update, :destroy, :show]

  include Pagy::Backend

  def index
    params[:per_page] ||= 10
    params[:page] ||= 1

    services = policy_scope(Service).contains(filter_params[:query]).sort_by &:name
    services = policy_scope(Service).sort_by &:name if services.empty?

    @pagy, @services = pagy_array(services, items: params[:per_page])
  end

  def new
    @service = Service.new(created_by_user: current_user)
    authorize(@service)
  end

  def create
    @service = Service.new(service_params.merge(created_by_user: current_user))
    authorize(@service)

    if @service.save
      redirect_to service_path(@service), flash: { success: t(:success, scope: [:services, :create]) }
    else
      render :new
    end
  end

  def edit_confirm
    @service = Service.find_by_slug(service_params[:slug])
  end

  def destroy
    ServiceEnvironment.all_slugs.each do |env|
      deployment = DeploymentService.last_status(service: @service, environment_slug: env)
      unless deployment.nil?
        UndeployServiceJob.perform_later(env: env.to_s, service_slug: @service.slug)
      end
    end

    @service.destroy!
    redirect_to services_path, flash: { success: t(:success, scope: [:services, :destroy], service: @service.name) }
  end

  def update
    if params[:commit] == t('services.edit_confirm.confirm') || @service.slug == service_params[:slug]
      redirect(@service, service_params)
    elsif @service.slug != service_params[:slug]
      render :edit_confirm
    end
  end

  def show
    @status_by_environment = ServiceDeploymentStatus.all(@service)
  end

  private

  def load_and_authorize_resource!
    @service = Service.find_by_slug(params[:slug])
    authorize(@service)
  end

  def service_params
    params[:service].permit([:git_repo_url, :name, :slug, :deploy_key])
  end

  def filter_params
    params.permit([:query])
  end

  def redirect(service, params)
    if @service.update(params)
      redirect_to service_path(service), flash: { success: t(:success, scope: [:services, :update], service: @service.name) }
    else
      render :edit
    end
  end
end

app/helpers/service_helper.rb
module ServiceHelper
  include Pagy::Frontend
end

app/views/services/_environment.html.haml
%tr{ id: environment.status_environment_slug }
  %th
    = form_environment(environment.status_environment_slug)
  %td
    - if environment.status_url.present?
      = link_to(environment.status_url, environment.status_url)
    - else
      \-

app/views/services/_filter.html.haml
= form_tag(services_path, method: :get) do
  = label_tag I18n.t('services.filter.label')
  = text_field_tag :query, params[:query], class: 'form-control'
  = submit_tag I18n.t('services.filter.submit'), class: 'button button-cta', name: nil

app/views/services/_form.html.haml
= form_for service do |f|
  .form-group
    = f.text_field :name, required: true, maxlength: 128
  .form-group
    = f.text_field :slug, maxlength: 64
  .form-group
    = f.text_field :git_repo_url, maxlength: 2048, required: true
  .form-group
    = f.text_area :deploy_key, maxlength: 4096
  .form-group
    = f.submit button_label, class: 'button button-cta'

app/views/services/_header.html.haml
%h1.heading-xlarge
  = service.name

%p
  = render partial: 'services/links', locals: {service: service}

app/views/services/_links.html.haml
%nav#service-links.inline-nav
  %ul
    %li
      - if current_action?(controller: :services, action: :show)
        %span= t('.urls')
      - else
        = link_to t('.urls'), service_path(service)
    %li
      - if current_action?(controller: 'services/config_params', action: :index)
        %span= t('.config_params')
      - else
        = link_to t('.config_params'), service_config_params_path(service)
    %li
      - if current_action?(controller: 'services/permissions')
        %span= t('.permissions')
      - else
        = link_to t('.permissions'), service_permissions_path(service)
    %li
      - if current_action?(controller: 'services/deployments')
        %span= t('.deployments')
      - else
        = link_to t('.deployments'), status_service_deployments_path(service)

app/views/services/_remove.html.haml
%div.pad-top
  %div.notice
    %p.pad-top-small
      = t(:warning_html, scope: [:services, :show], git_repo_url: service.git_repo_url)
    %p.pad-top-small
      = link_to t('services.show.delete'),
            service_path(service),
            class: 'button warning',
            method: :delete,
            data: { confirm: t('services.service.delete_confirm', service: service.name),
                    disable_with: t('services.service.deleting') }

app/views/services/_service.html.haml
%tr
  %td
    = link_to service.name, service_path(service)
  %td.actions
    - if can?(:edit, service)
      = link_to t('.edit'), edit_service_path(service)
    - if can?(:destroy, service)
      = link_to t('.delete'),
                  service_path(service),
                  method: :delete,
                  data: { confirm: t('.delete_confirm', service: service.name),
                          disable_with: t('.deleting') }

app/views/services/edit.html.haml
%h1.heading-xlarge
  = t('.heading', name: @service.name)

= GovukElementsErrorsHelper.error_summary @service,
  t(:errors_intro, scope: [:shared]), ''

= render partial: 'services/form', locals: {service: @service, button_label: t('.form.submit') }

app/views/services/edit_confirm.html.haml
%h1.heading-xlarge
  = t('services.edit_confirm.heading', name: @service.name)

%p.lede
  = t('services.update.confirm')

= form_for @service, method: :patch do |f|
  = f.hidden_field :name, value: params[:service][:name]
  = f.hidden_field :slug, value: params[:service][:slug]
  = f.hidden_field :git_repo_url, value: params[:service][:git_repo_url]
  = link_to t('services.edit_confirm.dismiss'), edit_service_path(@service), class: 'button button-cta'
  = f.submit t('services.edit_confirm.confirm'), class: 'button button-cta'

app/views/services/index.html.haml
%div
  %h1.heading-xlarge
    = t('.heading')

%div.grid-row.pad-bottom
  %div.column-one-third
    = link_to t('.new_service'), new_service_path, class: 'button button-cta'
  %div.column-two-thirds.right-align
    = render partial: 'filter'

- if @services.empty?
  %p
    = t('.no_services_yet')
- else
  %table
    %thead
      %th{ scope: 'col' }
        = t('.name')
      %th{ scope: 'col' }
        = t('.actions')
    %tbody
      = render partial: 'service', collection: @services
%div.pad-top
= pagy_nav(@pagy).html_safe

app/views/services/new.html.haml
%h1.heading-xlarge
  = t('.heading')

= GovukElementsErrorsHelper.error_summary @service,
  t(:errors_intro, scope: [:shared]), ''

= render partial: 'services/form', locals: {service: @service, button_label: t('.form.submit')}

app/views/services/show.html.haml
= render partial: 'services/header', locals: {service: @service}

%table
  %thead
    %tr

  %tbody
    = render partial: 'environment', collection: @status_by_environment
= render partial: 'remove', locals: {service: @service }