config/routes.rb
Rails.application.routes.draw do
  # Auth0 routes
  get "/auth/oauth2/callback" => "auth0#callback", as: 'auth0_callback'
  get "/auth/failure" => "auth0#failure"

  if Rails.env.development?
    post '/auth/developer/callback' => 'auth0#developer_callback'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/health' => 'health#show'
  get '/ping.json' => 'ping#show'
  get '/dashboard' => 'dashboard#show'
  get '/welcome' => 'welcome#show'
  get '/signup_not_allowed' => 'user_sessions#signup_not_allowed', as: 'signup_not_allowed'
  get '/signup_error/:error_type' => 'user_sessions#signup_error', as: 'signup_error'
  get '/' => 'home#show', as: 'root'

  resources :teams, param: :slug do
    scope :module => 'teams' do
      resources :members
      resources :permissions
    end
  end

  resources :services, param: :slug do
    scope :module => 'services' do
      resources :config_params, path: 'configuration'
      resources :permissions, controller_name: :service_permissions
      resources :deployments, controller_name: :service_deployments do
        get 'status', on: :collection, to: 'deployments#status'
        get '(/:env)', on: :collection, to: 'deployments#index', as: 'with_env', constraints: ServiceEnvironment::RoutingConstraint.new
        get 'log', on: :member, to: 'deployments#log'
      end
    end
  end


  resource :user
  resource :user_session, only: [:destroy]

  # global options responder -> makes sure OPTION request for CORS endpoints work
  match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
end

app/views/layouts/_debug.html.haml
%summary
  %span.summary
    = var_name
  .panel.panel-border-narrow
    %pre
      = var.inspect

app/views/layouts/_flashes.html.haml
- for key in flash.keys
  - unless flash[key].blank?
    %div{ class: "flash flash-#{key.to_s}" }
      = flash[key].html_safe

app/views/layouts/_header.html.erb
  <div class="header-wrapper">
    <div class="header-global">
      <div class="header-logo">
        <a href="https://www.gov.uk" title="Go to the GOV.UK homepage" id="logo" class="content">
          <img src="<%= image_path('justice_logo.png')%>" width="254" height="66" alt="Ministry of Justice logo">
        </a>
      </div>
    </div>

    <div class="header-proposition">
      <div class="content">
        <a href="#proposition-links" class="js-header-toggle menu">Menu</a>
        <nav id="proposition-menu">
          <a href="/" id="proposition-name">Form Builder - Publisher</a>
          <ul id="proposition-links">
            <li><a href="https://www.gov.uk/service-manual/service-standard">Digital Service Standard</a></li>
            <li><a href="https://www.gov.uk/service-toolkit">Service Toolkit</a></li>
            <li><a href="https://www.gov.uk/service-manual">Service Manual</a></li>
            <li><a href="https://www.gov.uk/contact/govuk">Feedback</a></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>

app/views/layouts/_unsigned_user_nav.html.erb
<ul id="proposition-links">
  <li>
    <% if Rails.env.development? %>
      <%= link_to t('.sign_in'), '/auth/developer', method: :post %>
    <% else %>
      <%= link_to t('.sign_in'), '/auth/auth0', method: :post %>
    <% end %>
  </li>
</ul>

app/views/layouts/_user_nav.html.haml
%ul#proposition-links
  %li
    = link_to t('.services'), services_path
  %li
    = link_to t('.create_form'), new_service_path
  %li
    = link_to t('.teams'), '/teams'
  %li
    = link_to t('.profile'), edit_user_path
  %li
    .sign-out
      = button_to t('.sign_out'), user_session_path, method: :delete, class: 'styled-as-link'

app/views/layouts/application.html.haml
= content_for :head do
  = stylesheet_link_tag "application.css"
  = csrf_meta_tags

= content_for :page_title do
  = t('.title')

= content_for :logo_link_title do
  = t('.logo_link_title')

= content_for :body_end do
  .javascript
    = javascript_include_tag "application.js"

= content_for :homepage_url do
  = root_url

= content_for :header_class do
  = "with-proposition"

= content_for :proposition_header do
  .header-proposition
    .content
      / no-js
      = link_to 'Menu', '#proposition-links', class: 'js-header-toggle menu'

      %nav#proposition-menu
        = link_to t('.title'), root_url, id: 'proposition-name'

        - if current_user
          = render partial: 'layouts/user_nav'
        - else
          = render partial: 'layouts/unsigned_user_nav'

= content_for :content do
  %main{ class: "content inner cf", id: "content", role: "main" }

    = render partial: 'layouts/flashes'

    = yield

= render template: "layouts/govuk_template"